# Generated by Django 5.2.1 on 2025-05-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
