# Generated by Django 5.2.1 on 2025-05-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0002_vehicle_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
