# Generated by Django 5.2.1 on 2025-05-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='seller_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('confirm', 'Confirm'), ('cancel', 'Cancel')], default='confirm', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('confirm', 'Confirm'), ('cancel', 'Cancel')], default='confirm', max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='buyer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
