# Generated by Django 5.2.1 on 2025-05-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_purchases', '0002_purchase_seller_name_purchase_status_sale_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirm', 'Confirm'), ('cancel', 'Cancel')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirm', 'Confirm'), ('cancel', 'Cancel')], default='draft', max_length=10),
        ),
    ]
