# Generated by Django 5.2.1 on 2025-05-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_purchases', '0003_alter_purchase_status_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
