# Generated by Django 5.2.1 on 2025-05-16 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_purchases', '0005_purchase_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='price',
            new_name='purchase_price',
        ),
    ]
