version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/django/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/vue/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    stdin_open: true
    tty: true

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: vehicle_db
      POSTGRES_USER: fajar
      POSTGRES_PASSWORD: fajar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data: