# Generated by Django 5.2.1 on 2025-05-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_token_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
